version: 0.4.0

# considered years for output data
years : [2020, 2025, 2030, 2035, 2040, 2045, 2050]

# Macroregion selection. Data with specific region definition override the default value. 
macroregion: "LATAM"  #Options: LATAM

expectation : "" # tech data uncertainty, possible options [None, "optimist", "pessimist"]

rate_inflation : 0.02

#year for EUR outputs
#NB: 2015 is standard year in DEA, and DEA is NOT yet adjusted
#if this is changed, only non-DEA
# DEA takes for solar PV eur_year 2020!
eur_year : 2015

# add solar from different source
solar_utility_from_vartiaien : false
solar_rooftop_from_etip : false

# add fuel cell/electrolysis efficiencies from Budischak (DEA assumptions very conservative)
h2_from_budischak : false
dea_electrolysis: '86 PEMEC 100MW' #'86 AEC 100MW', #'88 Alkaline Electrolyser',

# add and overwrite with fraunhofer iee data
use_fraunhofer_iee: True

# remove grid connection costs from DEA for offwind because they are calculated
# seperately in pypsa-eur
offwind_no_gridcosts : true

desalination:
    salinity: 35 # in PSU (Practical Salinity Unit) = kg/m^3


ndigits: 2