version: 0.9.0

# considered years for output data
years : [2020, 2025, 2030, 2035, 2040, 2045, 2050]

expectation : "" # tech data uncertainty, possible options [None, "optimist", "pessimist"]

#year for EUR outputs
eur_year : 2023

# add solar from different source
solar_utility_from_vartiaien : false
solar_rooftop_from_etip : false

energy_storage_database:
    h2_from_budischak: false  # add fuel cell/electrolysis efficiencies from Budischak (DEA assumptions very conservative)
    ewg_home_battery: true  # add home battery data derived from DEA data and EWG study
    pnnl_energy_storage:
        add_data: true  # add storage data mainly from PNNL
        approx_beyond_2030: ["same_as_2030"]  # ["geometric_series"] or ["same_as_2030"]

# add and overwrite with manual inputs in the order of the file names.
manual_inputs: ["manual_input.csv","fraunhofer_iee.csv","fraunhofer_iee-fuels_ptx.csv", "fraunhofer_iee-SA_study.csv"] #,"fraunhofer_iee-chile.csv"

# remove grid connection costs from DEA for offwind because they are calculated
# seperately in pypsa-eur
offwind_no_gridcosts : true

desalination:
    salinity: 35 # in PSU (Practical Salinity Unit) = kg/m^3

ndigits: 4
